Traceback (most recent call last):
  File "/home/panxopanza/miniconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/panxopanza/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/panxopanza/miniconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/panxopanza/miniconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/panxopanza/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/panxopanza/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/panxopanza/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from ipywidgets import interact

@interact( N=(1,1000,1), 
           t=(-10,10,0.1),
           sig=(0,1,0.01))
def g(N=1000, t=0, sig=0.3):
    return plot_light_packet(N,t,sig)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[3], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mipywidgets[39;00m [38;5;28;01mimport[39;00m interact
[1;32m      3[0m [38;5;129m@interact[39m( N[38;5;241m=[39m([38;5;241m1[39m,[38;5;241m1000[39m,[38;5;241m1[39m), 
[1;32m      4[0m            t[38;5;241m=[39m([38;5;241m-[39m[38;5;241m10[39m,[38;5;241m10[39m,[38;5;241m0.1[39m),
[1;32m      5[0m            sig[38;5;241m=[39m([38;5;241m0[39m,[38;5;241m1[39m,[38;5;241m0.01[39m))
[1;32m      6[0m [38;5;28;01mdef[39;00m [38;5;21mg[39m(N[38;5;241m=[39m[38;5;241m1000[39m, t[38;5;241m=[39m[38;5;241m0[39m, sig[38;5;241m=[39m[38;5;241m0.3[39m):
[1;32m      7[0m     [38;5;28;01mreturn[39;00m plot_light_packet(N,t,sig)

[0;31mModuleNotFoundError[0m: No module named 'ipywidgets'

