Traceback (most recent call last):
  File "/home/panxopanza/miniconda3/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/panxopanza/miniconda3/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/panxopanza/miniconda3/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/panxopanza/miniconda3/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/panxopanza/miniconda3/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/panxopanza/miniconda3/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/panxopanza/miniconda3/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
lam = np.linspace(0.3,1.0,100) # espectro de longitudes de onda
tfilm = 1                      # espesor en mm
N = (1.0,1.33,1.0)             # indice de refracci√≥n superior, intermedio e inferior
fv = 0.001                     # fracci√≥n de vol√∫men de los poros
D = 0.3                        # di√°metro de los poros (micrones)
Np = nk.SiO2(lam)              # √≠ndice de refracci√≥n part√≠cula

Ttot, Rtot, Tspec, Rspec = rt.adm_sphere(lam,tfilm,N,fv,D,Np)

plt.plot(lam,Rtot,'-r',label='$R_\mathrm{tot}$')
plt.plot(lam,Ttot,'-b',label='$T_\mathrm{tot}$')
plt.plot(lam,Rspec,'--r',label='$R_\mathrm{spec}$')
plt.plot(lam,Tspec,'--b',label='$T_\mathrm{spec}$')
plt.xlabel('Longitud de onda ($\mu$m)')
plt.ylabel('Reflectividad / Transmisividad')
plt.title(r'S√≠lice suspendido en agua (fv = %.1f %% v/v)' % (fv*100))
plt.legend()
plt.ylim(0,1)
plt.show()
------------------

----- stderr -----
<>:10: SyntaxWarning: invalid escape sequence '\m'
<>:11: SyntaxWarning: invalid escape sequence '\m'
<>:12: SyntaxWarning: invalid escape sequence '\m'
<>:13: SyntaxWarning: invalid escape sequence '\m'
<>:14: SyntaxWarning: invalid escape sequence '\m'
<>:10: SyntaxWarning: invalid escape sequence '\m'
<>:11: SyntaxWarning: invalid escape sequence '\m'
<>:12: SyntaxWarning: invalid escape sequence '\m'
<>:13: SyntaxWarning: invalid escape sequence '\m'
<>:14: SyntaxWarning: invalid escape sequence '\m'
/tmp/ipykernel_1344/901086605.py:10: SyntaxWarning: invalid escape sequence '\m'
  plt.plot(lam,Rtot,'-r',label='$R_\mathrm{tot}$')
/tmp/ipykernel_1344/901086605.py:11: SyntaxWarning: invalid escape sequence '\m'
  plt.plot(lam,Ttot,'-b',label='$T_\mathrm{tot}$')
/tmp/ipykernel_1344/901086605.py:12: SyntaxWarning: invalid escape sequence '\m'
  plt.plot(lam,Rspec,'--r',label='$R_\mathrm{spec}$')
/tmp/ipykernel_1344/901086605.py:13: SyntaxWarning: invalid escape sequence '\m'
  plt.plot(lam,Tspec,'--b',label='$T_\mathrm{spec}$')
/tmp/ipykernel_1344/901086605.py:14: SyntaxWarning: invalid escape sequence '\m'
  plt.xlabel('Longitud de onda ($\mu$m)')
----- stderr -----
/tmp/ipykernel_1344/901086605.py:10: SyntaxWarning: invalid escape sequence '\m'
  plt.plot(lam,Rtot,'-r',label='$R_\mathrm{tot}$')
/tmp/ipykernel_1344/901086605.py:11: SyntaxWarning: invalid escape sequence '\m'
  plt.plot(lam,Ttot,'-b',label='$T_\mathrm{tot}$')
/tmp/ipykernel_1344/901086605.py:12: SyntaxWarning: invalid escape sequence '\m'
  plt.plot(lam,Rspec,'--r',label='$R_\mathrm{spec}$')
/tmp/ipykernel_1344/901086605.py:13: SyntaxWarning: invalid escape sequence '\m'
  plt.plot(lam,Tspec,'--b',label='$T_\mathrm{spec}$')
/tmp/ipykernel_1344/901086605.py:14: SyntaxWarning: invalid escape sequence '\m'
  plt.xlabel('Longitud de onda ($\mu$m)')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[27], line 8[0m
[1;32m      5[0m D [38;5;241m=[39m [38;5;241m0.3[39m                        [38;5;66;03m# di√°metro de los poros (micrones)[39;00m
[1;32m      6[0m Np [38;5;241m=[39m nk[38;5;241m.[39mSiO2(lam)              [38;5;66;03m# √≠ndice de refracci√≥n part√≠cula[39;00m
[0;32m----> 8[0m Ttot, Rtot, Tspec, Rspec [38;5;241m=[39m rt[38;5;241m.[39madm_sphere(lam,tfilm,N,fv,D,Np)
[1;32m     10[0m plt[38;5;241m.[39mplot(lam,Rtot,[38;5;124m'[39m[38;5;124m-r[39m[38;5;124m'[39m,label[38;5;241m=[39m[38;5;124m'[39m[38;5;124m$R_[39m[38;5;124m\[39m[38;5;124mmathrm[39m[38;5;132;01m{tot}[39;00m[38;5;124m$[39m[38;5;124m'[39m)
[1;32m     11[0m plt[38;5;241m.[39mplot(lam,Ttot,[38;5;124m'[39m[38;5;124m-b[39m[38;5;124m'[39m,label[38;5;241m=[39m[38;5;124m'[39m[38;5;124m$T_[39m[38;5;124m\[39m[38;5;124mmathrm[39m[38;5;132;01m{tot}[39;00m[38;5;124m$[39m[38;5;124m'[39m)

[0;31mValueError[0m: not enough values to unpack (expected 4, got 2)

